#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root."
    exit 1
fi

dnf remove -y firefox firefox-langpacks gnome-maps totem \
    gnome-boxes gnome-weather rhythmbox baobab libreoffice-* \
    gnome-connections gnome-logs mediawriter gnome-terminal* \
    simple-scan gnome-contacts gnome-abrt gnome-font-viewer \
    gnome-tour gnome-calculator evince gnome-system-monitor

dnf copr enable -y dusansimic/themes

dnf install -y adw-gtk3-theme morewaita-icon-theme \
    cascadia-code-nf-fonts rsms-inter-fonts

dnf install -y micro wl-clipboard systemd-container \
    stow p7zip p7zip-plugins

dnf install -y wireshark strace nmap httpie

dnf install -y ansible azure-cli awscli2 opentofu htop \
    @development-tools httpie btop gnome-console

dnf install -y flatseal transmission

dnf autoremove -y
