#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root."
    exit 1
fi

set -eux

# fonts
curl https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-$(rpm -E %fedora)/peterwu-iosevka-fedora-$(rpm -E %fedora).repo > /etc/yum.repos.d/iosevka.repo

# base removal
rpm-ostree override remove firefox firefox-langpacks gnome-software gnome-software-rpm-ostree

# base addition
rpm-ostree install gnome-shell-extension-appindicator gnome-shell-extension-just-perfection distrobox \
            adw-gtk3-theme easyeffects iosevka-fonts stow papirus-icon-theme
