#!/bin/bash

if [ "$EUID" -eq 0 ]; then
	echo "Please don't run this as root."
	exit 1
fi

set -eux

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.config/Code/User
mkdir -p $HOME/.config/plasma-workspace/env
rm $HOME/.bashrc $HOME/.bash_profile $HOME/.bash_logout

# symlink configs
stow Home -t ~/

# asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch $(curl -s "https://api.github.com/repos/asdf-vm/asdf/releases/latest" | jq -r .tag_name)

. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"

asdf plugin add golang
asdf plugin add nodejs

asdf install golang latest
asdf global golang latest

asdf install nodejs latest
asdf global nodejs latest

# flatpaks
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub com.valvesoftware.Steam 
