#!/bin/bash

if [ "$EUID" -eq 0 ]; then
	echo "Please don't run this as root."
	exit 1
fi

set -eux

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.config/Code/User
rm $HOME/.bashrc $HOME/.bash_profile $HOME/.bash_logout

# symlink configs
stow Home -t ~/

# asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch $(curl -s "https://api.github.com/repos/asdf-vm/asdf/releases/latest" | jq -r .tag_name)

. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"

asdf plugin add golang
asdf plugin add kubectl
asdf plugin add nodejs

asdf install golang latest
asdf global golang latest

asdf install kubectl latest
asdf global kubectl latest

asdf install nodejs latest
asdf global nodejs latest

# vscode extensions
pkglist=(
    golang.go
    ms-python.python
    ms-python.vscode-pylance
    ritwickdey.liveserver
    redhat.vscode-yaml
    bradlc.vscode-tailwindcss
    github.github-vscode-theme
)

for i in ${pkglist[@]}; do
    code --install-extension $i
done

# flatpaks
flatpak remove --all -y

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub org.chromium.Chromium com.valvesoftware.Steam org.prismlauncher.PrismLauncher \
	org.gnome.clocks org.gnome.Calendar org.gnome.Evince org.gnome.Loupe org.gnome.World.Secrets \
	com.github.wwmm.easyeffects com.github.tchx84.Flatseal com.dec05eba.gpu_screen_recorder \
	de.haeckerfelix.Fragments io.github.celluloid_player.Celluloid \
	org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark
