#!/usr/bin/env bash

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this as root."
    exit 1
fi

set -eux

mkdir -p $HOME/.local/bin
rm -rf $HOME/.mozilla
rm $HOME/.bashrc $HOME/.bash_profile $HOME/.bash_logout

# configs
stow Home -t ~/

# asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch $(curl -s "https://api.github.com/repos/asdf-vm/asdf/releases/latest" | jq -r .tag_name)

. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"

asdf plugin add golang
asdf plugin add nodejs
asdf plugin add terraform
asdf plugin add kubectl

asdf install golang latest
asdf global golang latest

asdf install nodejs latest
asdf global nodejs latest

asdf install terraform latest
asdf global terraform latest

asdf install kubectl latest
asdf global kubectl latest

# flatpaks
flatpak remove --all -y

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark \
  org.gnome.Evince org.gnome.Loupe org.gnome.clocks org.gnome.Calendar io.mpv.Mpv \
  com.github.tchx84.Flatseal com.github.wwmm.easyeffects org.gnome.World.Secrets \
  com.brave.Browser org.prismlauncher.PrismLauncher com.valvesoftware.Steam \
  com.jetbrains.GoLand it.mijorus.gearlever 

# setup
gnome-extensions disable background-logo@fedorahosted.org
gnome-extensions enable just-perfection-desktop@just-perfection

gsettings set org.gnome.shell.keybindings toggle-application-view []
gsettings set org.gnome.shell.keybindings toggle-overview []
gsettings set org.gnome.shell.keybindings toggle-quick-settings []
gsettings set org.gnome.shell.extensions.just-perfection search false
gsettings set org.gnome.shell.extensions.just-perfection window-picker-icon false
gsettings set org.gnome.shell.app-switcher current-workspace-only true
gsettings set org.gnome.shell.window-switcher app-icon-mode "thumbnail-only"

gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.mutter center-new-windows true

gsettings set org.gnome.desktop.wm.preferences num-workspaces 6
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>a']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>s']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>f']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>c']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>x']"
gsettings set org.gnome.desktop.session idle-delay "uint32 0"
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
gsettings set org.gnome.desktop.interface monospace-font-name 'monospace 12'

gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<Super>Return"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "gnome-terminal"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Terminal"
