#!/bin/bash

set -eux

# vscodium
sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo

# iosevka fonts
sudo dnf copr enable peterwu/iosevka -y

# additional packages
sudo dnf install -y adw-gtk3-theme iosevka-fonts codium make python-pip 

# vscodium packages
pkglist=(
    golang.go
)

for i in ${pkglist[@]}; do
    codium --install-extension $i
done

# export 
distrobox-export --bin $(which codium)
